spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 20881
eureka:
  instance:
    hostname: localhost
    statusPageUrl: http://${spring.cloud.client.ipAddress}/swagger-ui.html
  server:  
    enableSelfPreservation: false  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
