
###################  项目启动端口  ###################
server:
  port: 8087
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 100000000
      max-file-size: 100000000

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapperLocations: classpath*:mapper/*/*.xml
  typeAliasesPackage: com.fhs.file.bean;


eureka:
    client:
      healthcheck:
        enabled: true

