spring:
  cloud:
    gateway:
      routes:
        - id:  basic ##路由 ID（不是网关ID），保持唯一
          #目标服务地址 （加 lb 根据注册中心服务名匹配）
          uri: lb://basic
          predicates:
            #   #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）
            - Path=/basic/**
          #必须加上StripPrefix=1，否则访问服务时会带上provider
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
