
###################  项目启动端口  ###################
server:
  port: 8088

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapperLocations: classpath*:mapper/*/*.xml
  typeAliasesPackage: com.fhs.workflow.bean;

eureka:
  instance:
    appname: flow


spring:
  session:
    store-type: none

  #Activiti property configuration
  activiti:
    database-schema-update: false
    job-executor-activate: true
    history-level: full
    check-process-definitions: false
    ext:
      database-schema-update: false
  jpa:
    show-sql: true
fhs:
  activiti:
    createtb: true