# Mysql数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://12.157.62.164:3306/fhs-demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: wanglei1992
  redis:
    database: 11
    host: 12.157.62.164
    password: wanglei1992
    port: 16379
#JDK17 用户请设置application.yaml的 easy-trans.is-enable-tile 为false
