###################  项目启动端口  ###################
server:
  port: 8089
  context-path: /
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.basics.dox;
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
easy-trans:
  autotrans:
    package: com.fhs.**.service.**;com.fhs.**.dao.**;
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: true
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true
  #关闭springcloud支持
  is-enable-cloud: false
fhs:
  vue:
    is-verification: true
  autoware:
    package: com.fhs.*;com.fhs.*.*;
  autodel:
    service-packege: com.**.service.**
  login:
    error-pass-lock-times: 100 #2次密码输入错误就锁定
    user-lock-seconds: 60 ##10秒解除锁定
  mybatis-jpa:
    #多个用;分隔
    entity-package: com.**.**.po
    mapper-package: com.**.**.mapper
  safe:
    enable-xss: true #xss注入控制
  session:
    timeout: 1800
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin: #声明式事物 类名包含service的，但是不包含api，action,dao的类开启
    contains: service
    not-contains: api;controller;mapper
    #声明式事物管理，具体请访问官网
    package: com.fhs;
  cache: #CacheUpdateManager 支持缓存包扫码
    packages: com.fhs.**.service.impl
  disable-apollo: true
  swagger: # ip:port/doc.html 是swagger-ui的地址,本插件用的是swagger-bootstrap-ui
    enable: true
    basepackage: com.fhs
    service:
      description: 项目api
      developer: fhs developers
      name: 公共接口文档
  operator-log:
    enable: true

  path: "{
        'fileSavePath': 'c:/flies'
        }"
  other: "{
          'isDevModel': 'true',
          'access_token_time_out_second': '500',
          'systemTitle': 'FHS演示系统'
          }"
  wxmini:
    enable: true
    appid: wx42e064f24b987ca0
    secret: 0735b2cc9adeb123e3dd321253bf27e6
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: fhs_admin_app
  redis:
    database: 11
    # 最大连接数
    maxTotal: 5000
    # 最大空闲连接数
    maxIdle: 1000
    # 建立连接时，最大等待时间
    maxWaitMillis: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10
    host: 192.168.0.213
    password: 123456
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:mysql://192.168.0.213:3306/ofpl?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    validationQuery: select 'x'

logging:
  config: classpath:logback-fhs.xml
  level:
    com.fhs.basics: debug
    com.fhs.bislogger: debug
logback:
  root:
    level: INFO
  file:
    #日志存放路径
    dir: c:/logs/all_in_one/

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: linkedhashmap
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
  remote: #阿里的jetcache2级缓存
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      asyncResultTimeoutInMillis: 3000
      uri:
        - redis://123456@192.168.0.213:6379/11  #redis://密码@IP:端口/库
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
# 监控启动时间
management:
  endpoints:
    web:
      exposure:
        include: startup