# Mysql数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.213:3306/energy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    database: 11
    host: 192.168.0.213
    password: 123456
    port: 6379
#JDK17 用户请设置application.yaml的 easy-trans.is-enable-tile 为false 不然会报一个cglib的错误
fhs:
  beetl:
    enable: true

  path: "{
        'fileSavePath': 'c:/flies'
        }"

  other: "{
          'isDevModel': 'true',
          'access_token_time_out_second': '500',
          'systemTitle': 'FHS演示系统'
          }"