# postgre数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://192.168.0.213:5432/fhs-demo
    username: postgres
    password: 123456
  redis:
    database: 11
    host: 192.168.0.213
    password: 123456
    port: 6379
#JDK17 用户请设置application.yaml的 easy-trans.is-enable-tile 为false 不然会报一个cglib的错误
