###################  项目启动端口  ###################
server:
  port: 8082
  context-path: /
  tomcat:
    uri-encoding: UTF-8
# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.system.bean;com.fhs.ucenter.bean;com.fhs.fileService.bean;com.fhs.pubservice.bean;com.fhs.file.bean;

fhs:
  autoware:
    package: com.fhs.*;com.fhs.*.*;
  autodel:
    service-packege: com.**.service.**
  login:
    #是否开启cas默认关闭
    enable-cas: true
    cas:
      client-base-path: http://127.0.0.1:8082/ #当前项目的访问路径
      server-url: http://cas.fhs.xhb.com # cas地址
  mybatis-jpa:
    #多个用;分隔
    entity-package: com.**.**.bean
    mapper-package: com.**.**.dao
  safe:
    enable-xss: true #xss注入控制
  session:
    timeout: 1800
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin: #声明式事物 类名包含service的，但是不包含api，action,dao的类开启
    contains: service
    not-contains: api;controller;mapper
    #声明式事物管理，具体请访问官网
    package: com.fhs;
  cache: #CacheUpdateManager 支持缓存包扫码
    packages: com.fhs.**.service.impl
  swagger: # ip:port/doc.html 是swagger-ui的地址,本插件用的是swagger-bootstrap-ui
    enable: false
    basepackage: com.fhs
    service:
      description: 项目api
      developer: fhs developers
      name: 公共接口文档
  path: "{
            'basePath': 'http://127.0.0.1:8082/',
            'staticPath': 'http://static.fhs.xhb.com/',
            'fhs_basics_url': 'http://127.0.0.1:8082/',
            'fileSavePath': 'c:/flies',
            'jbpmFilePath': 'c:/flies/jbpm/xml',
            'loginOutUrl': 'http://127.0.0.1:8082/ms/logout',
            'fhs_file_basePath': 'http://127.0.0.1:8082/',
            'base_index_right': 'http://127.0.0.1:8082/b/page-ms-index/index_right',
            'work_flow_url': 'http://127.0.0.1:8082/'
            }"
  other: "{
          'isDevModel': 'true',
          'access_token_time_out_second': '500',
          'base_system_title': 'FHS演示系统',
          'base_system_name' : 'FHS演示系统'
          }"
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.fhs.xhb.com:8848
  main:
    allow-bean-definition-overriding: true
  application:
    name: basics
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10
    host: 192.168.0.213
    password: 123456
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 20
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    name: base_business
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: trueserver
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.213:3306/fhs_base_business?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    validationQuery: select 'x'

seata:
  enabled: true
  application-id: client
  tx-service-group: fhs-seata-group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.0.213:8848
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 192.168.0.213:8848
      group: SEATA_GROUP
      namespace:


logging:
  config: classpath:logback_fhs.xml
  level:
    com.fhs.basics: debug
    com.fhs.pagex: debug

logback:
  #这里可以配置logstash ip和端口
  elk:
    host: 172.16.57.109:9250
  root:
    level: INFO
  file:
    #日志存放路径
    dir: c:/logs/basics/

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: linkedhashmap
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
  remote: #阿里的jetcache2级缓存
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      asyncResultTimeoutInMillis: 3000
      uri:
        - redis://123456@192.168.0.213:6379/3  #redis://密码@IP:端口/库
