
###################  项目启动端口  ###################
server:
  port: 8081
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.system.bean;com.fhs.ucenter.bean;com.fhs.fileService.bean;com.fhs.pubservice.bean;

fhs:
  autoware:
    package: com.fhs.*;com.fhs.*.*;
  login:
    #是否开启cas默认关闭
    enable-cas: false
    #登录地址
    url: /page/login.jsp
  mybatis-jpa:
    #多个用;分隔
    entity-package: com.**.**.bean
    mapper-package: com.**.**.dao
  safe:
    enable-xss: true
  session:
    timeout: 1800
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin:
    contains: service
    not-contains: api;action;dao
    #声明式事物管理，具体请访问官网
    package: com.fhs;
  disable-apollo: true
spring:
    session:
        store-type: redis
    application:
      name: park_client
    mvc:
      view:
        prefix: /page/
        suffix: .jsp
    redis:
      database: 0
      password: 123456
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10
      host: 127.0.0.1
      port: 6379
      timeout: 6000
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      initialSize: 1
      maxActive: 20
      maxOpenPreparedStatements: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 1
      name: base_business
      password: 123456
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: trueserver
      timeBetweenEvictionRunsMillis: 60000
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.0.241:3306/fhs-demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
      username: root
      validationQuery: select 'x'


swagger:
  #第一个版本默认禁用了swagger，后面会放开，或者你自己在启动类加上加个@EnableSwagger2
  basepackage: com.fhs
  service:
    description: 项目api
    developer: fhs developers
    name: 公共接口文档

logging:
  config: classpath:logback_fhs.xml
  level:
    com.fhs.ucenter.dao: debug
    com.fhs.pagex: debug
    com.fhs.system.dao: debug

logback:
  #这里可以配置logstash ip和端口
  elk:
    host: 127.0.0.1:9250
  root:
    level: INFO
  file:
    #日志存放路径
    dir: c:/logs/base/

