
###################  项目启动端口  ###################
server:
  port: 80
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.system.bean;com.fhs.ucenter.bean;com.fhs.fileService.bean;com.fhs.pubservice.bean;com.fhs.file.bean;

fhs:
  autoware:
    package: com.fhs.*;com.fhs.*.*;
  login:
    #是否开启cas默认关闭
    enable-cas: false
    #登录地址
    url: /b/page/login
  mybatis-jpa:
    #多个用;分隔
    entity-package: com.**.**.bean
    mapper-package: com.**.**.dao
  safe:
    enable-xss: true #xss注入控制
  session:
    timeout: 1800
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin: #声明式事物 类名包含service的，但是不包含api，action,dao的类开启
    contains: service
    not-contains: api;action;dao
    #声明式事物管理，具体请访问官网
    package: com.fhs;
  path: "{
          'basePath': 'http://park.sxpartner.com/',
          'staticPath': 'http://park.sxpartner.com/',
          'fhs_basics_url': 'http://park.sxpartner.com/',
          'fileSavePath': 'c:/flies',
          'jbpmFilePath': 'c:/flies/jbpm/xml',
          'loginOutUrl': 'http://park.sxpartner.com/ms/logout',
          'fhs_file_basePath': 'http://park.sxpartner.com/',
          'base_index_right': 'http://park.sxpartner.com/b/page-ms-index/index_right',
          'redirect_login_url':'http://park.sxpartner.com/webApi/front/login?code=1',
          'work_flow_url': 'http://park.sxpartner.com/'
          }"
  other: "{
          'isDevModel': 'true',
          'access_token_time_out_second': '500',
          'base_system_title': 'FHS演示系统',
          'base_system_name' : 'FHS演示系统'
          }"
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: park_client
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 3
    # 最大连接数
    maxTotal: 5000
    # 最大空闲连接数
    maxIdle: 1000
    # 建立连接时，最大等待时间
    maxWaitMillis: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 20
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    name: base_business
    password: 123456
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: trueserver
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/fhs_base_business?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    validationQuery: select 'x'


swagger:
  #第一个版本默认禁用了swagger，后面会放开，或者你自己在启动类加上加个@EnableSwagger2
  basepackage: com.fhs
  service:
    description: 项目api
    developer: fhs developers
    name: 公共接口文档

logging:
  config: classpath:logback_fhs.xml
  level:
    com.fhs.ucenter.dao: debug
    com.fhs.pagex: debug
    com.fhs.system.dao: debug

logback:
  #这里可以配置logstash ip和端口
  elk:
    host: 127.0.0.1:9250
  root:
    level: INFO
  file:
    #日志存放路径
    dir: c:/logs/base/

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: linkedhashmap
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
  remote: #阿里的jetcache2级缓存
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      asyncResultTimeoutInMillis: 3000
      uri:
        - redis://123456@127.0.0.1:6379/3  #redis://密码@IP:端口/库
